// Generated TypeScript code from Protocol Buffers
// This file will be generated by scripts/generate-proto.sh

export * from "./blog_agent_pb";

// Export Connect service definitions if available
// Note: For Connect v2, we may need to manually create service definitions
// or use a different generation approach
try {
  // @ts-ignore - may not exist if using buf only
  export * from "./blog_agent_connect";
} catch {
  // Connect service definitions not available
  // They will be generated separately or created manually for Connect v2
}

