// @generated by protoc-gen-connect-es v0.13.0
// @generated from file blog_agent.proto (package blog_agent.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetBlogPostRequest, GetBlogPostResponse, GetBlogPostWithPromptsResponse, GetConversationLogRequest, GetConversationLogResponse, GetProcessingHistoryRequest, GetProcessingHistoryResponse, ListBlogPostsRequest, ListBlogPostsResponse, ListConversationLogsRequest, ListConversationLogsResponse, ProcessConversationRequest, ProcessConversationResponse } from "./blog_agent_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Blog Agent Service - 處理對話紀錄轉換為部落格文章
 *
 * @generated from service blog_agent.v1.BlogAgentService
 */
export declare const BlogAgentService: {
  readonly typeName: "blog_agent.v1.BlogAgentService",
  readonly methods: {
    /**
     * 處理對話紀錄並生成部落格文章
     *
     * @generated from rpc blog_agent.v1.BlogAgentService.ProcessConversation
     */
    readonly processConversation: {
      readonly name: "ProcessConversation",
      readonly I: typeof ProcessConversationRequest,
      readonly O: typeof ProcessConversationResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * 列出所有已處理的對話紀錄
     *
     * @generated from rpc blog_agent.v1.BlogAgentService.ListConversationLogs
     */
    readonly listConversationLogs: {
      readonly name: "ListConversationLogs",
      readonly I: typeof ListConversationLogsRequest,
      readonly O: typeof ListConversationLogsResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * 取得特定的對話紀錄
     *
     * @generated from rpc blog_agent.v1.BlogAgentService.GetConversationLog
     */
    readonly getConversationLog: {
      readonly name: "GetConversationLog",
      readonly I: typeof GetConversationLogRequest,
      readonly O: typeof GetConversationLogResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * 取得生成的部落格文章
     *
     * @generated from rpc blog_agent.v1.BlogAgentService.GetBlogPost
     */
    readonly getBlogPost: {
      readonly name: "GetBlogPost",
      readonly I: typeof GetBlogPostRequest,
      readonly O: typeof GetBlogPostResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * 取得部落格文章（包含結構化的 content blocks 和 prompt meta，用於 UI/UX）
     *
     * @generated from rpc blog_agent.v1.BlogAgentService.GetBlogPostWithPrompts
     */
    readonly getBlogPostWithPrompts: {
      readonly name: "GetBlogPostWithPrompts",
      readonly I: typeof GetBlogPostRequest,
      readonly O: typeof GetBlogPostWithPromptsResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * 列出所有部落格文章
     *
     * @generated from rpc blog_agent.v1.BlogAgentService.ListBlogPosts
     */
    readonly listBlogPosts: {
      readonly name: "ListBlogPosts",
      readonly I: typeof ListBlogPostsRequest,
      readonly O: typeof ListBlogPostsResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * 取得處理歷史
     *
     * @generated from rpc blog_agent.v1.BlogAgentService.GetProcessingHistory
     */
    readonly getProcessingHistory: {
      readonly name: "GetProcessingHistory",
      readonly I: typeof GetProcessingHistoryRequest,
      readonly O: typeof GetProcessingHistoryResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

