// @generated by protoc-gen-es v2.10.1
// @generated from file blog_agent.proto (package blog_agent.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file blog_agent.proto.
 */
export declare const file_blog_agent: GenFile;

/**
 * 處理對話紀錄請求
 *
 * @generated from message blog_agent.v1.ProcessConversationRequest
 */
export declare type ProcessConversationRequest = Message<"blog_agent.v1.ProcessConversationRequest"> & {
  /**
   * 檔案路徑
   *
   * @generated from field: string file_path = 1;
   */
  filePath: string;

  /**
   * 檔案格式
   *
   * @generated from field: blog_agent.v1.FileFormat file_format = 2;
   */
  fileFormat: FileFormat;

  /**
   * 檔案內容（二進位）
   *
   * @generated from field: bytes file_content = 3;
   */
  fileContent: Uint8Array;

  /**
   * 額外 metadata
   *
   * @generated from field: map<string, string> metadata = 4;
   */
  metadata: { [key: string]: string };
};

/**
 * Describes the message blog_agent.v1.ProcessConversationRequest.
 * Use `create(ProcessConversationRequestSchema)` to create a new message.
 */
export declare const ProcessConversationRequestSchema: GenMessage<ProcessConversationRequest>;

/**
 * 處理對話紀錄回應
 *
 * @generated from message blog_agent.v1.ProcessConversationResponse
 */
export declare type ProcessConversationResponse = Message<"blog_agent.v1.ProcessConversationResponse"> & {
  /**
   * 處理 ID (UUID)
   *
   * @generated from field: string processing_id = 1;
   */
  processingId: string;

  /**
   * 處理狀態
   *
   * @generated from field: blog_agent.v1.ProcessingStatus status = 2;
   */
  status: ProcessingStatus;

  /**
   * 錯誤訊息（如果失敗）
   *
   * @generated from field: string error_message = 3;
   */
  errorMessage: string;

  /**
   * 生成的部落格文章（如果成功）
   *
   * @generated from field: blog_agent.v1.BlogPost blog_post = 4;
   */
  blogPost?: BlogPost;
};

/**
 * Describes the message blog_agent.v1.ProcessConversationResponse.
 * Use `create(ProcessConversationResponseSchema)` to create a new message.
 */
export declare const ProcessConversationResponseSchema: GenMessage<ProcessConversationResponse>;

/**
 * 列出對話紀錄請求
 *
 * @generated from message blog_agent.v1.ListConversationLogsRequest
 */
export declare type ListConversationLogsRequest = Message<"blog_agent.v1.ListConversationLogsRequest"> & {
  /**
   * 每頁數量
   *
   * @generated from field: int32 page_size = 1;
   */
  pageSize: number;

  /**
   * 分頁 token
   *
   * @generated from field: string page_token = 2;
   */
  pageToken: string;

  /**
   * 語言篩選（可選）
   *
   * @generated from field: string language_filter = 3;
   */
  languageFilter: string;
};

/**
 * Describes the message blog_agent.v1.ListConversationLogsRequest.
 * Use `create(ListConversationLogsRequestSchema)` to create a new message.
 */
export declare const ListConversationLogsRequestSchema: GenMessage<ListConversationLogsRequest>;

/**
 * 列出對話紀錄回應
 *
 * @generated from message blog_agent.v1.ListConversationLogsResponse
 */
export declare type ListConversationLogsResponse = Message<"blog_agent.v1.ListConversationLogsResponse"> & {
  /**
   * @generated from field: repeated blog_agent.v1.ConversationLog conversation_logs = 1;
   */
  conversationLogs: ConversationLog[];

  /**
   * 下一頁 token
   *
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;

  /**
   * 總數
   *
   * @generated from field: int32 total_count = 3;
   */
  totalCount: number;
};

/**
 * Describes the message blog_agent.v1.ListConversationLogsResponse.
 * Use `create(ListConversationLogsResponseSchema)` to create a new message.
 */
export declare const ListConversationLogsResponseSchema: GenMessage<ListConversationLogsResponse>;

/**
 * 取得對話紀錄請求
 *
 * @generated from message blog_agent.v1.GetConversationLogRequest
 */
export declare type GetConversationLogRequest = Message<"blog_agent.v1.GetConversationLogRequest"> & {
  /**
   * 對話紀錄 ID (UUID)
   *
   * @generated from field: string conversation_log_id = 1;
   */
  conversationLogId: string;
};

/**
 * Describes the message blog_agent.v1.GetConversationLogRequest.
 * Use `create(GetConversationLogRequestSchema)` to create a new message.
 */
export declare const GetConversationLogRequestSchema: GenMessage<GetConversationLogRequest>;

/**
 * 取得對話紀錄回應
 *
 * @generated from message blog_agent.v1.GetConversationLogResponse
 */
export declare type GetConversationLogResponse = Message<"blog_agent.v1.GetConversationLogResponse"> & {
  /**
   * @generated from field: blog_agent.v1.ConversationLog conversation_log = 1;
   */
  conversationLog?: ConversationLog;
};

/**
 * Describes the message blog_agent.v1.GetConversationLogResponse.
 * Use `create(GetConversationLogResponseSchema)` to create a new message.
 */
export declare const GetConversationLogResponseSchema: GenMessage<GetConversationLogResponse>;

/**
 * 取得部落格文章請求
 *
 * @generated from message blog_agent.v1.GetBlogPostRequest
 */
export declare type GetBlogPostRequest = Message<"blog_agent.v1.GetBlogPostRequest"> & {
  /**
   * 部落格文章 ID (UUID)
   *
   * @generated from field: string blog_post_id = 1;
   */
  blogPostId: string;
};

/**
 * Describes the message blog_agent.v1.GetBlogPostRequest.
 * Use `create(GetBlogPostRequestSchema)` to create a new message.
 */
export declare const GetBlogPostRequestSchema: GenMessage<GetBlogPostRequest>;

/**
 * 取得部落格文章回應
 *
 * @generated from message blog_agent.v1.GetBlogPostResponse
 */
export declare type GetBlogPostResponse = Message<"blog_agent.v1.GetBlogPostResponse"> & {
  /**
   * @generated from field: blog_agent.v1.BlogPost blog_post = 1;
   */
  blogPost?: BlogPost;
};

/**
 * Describes the message blog_agent.v1.GetBlogPostResponse.
 * Use `create(GetBlogPostResponseSchema)` to create a new message.
 */
export declare const GetBlogPostResponseSchema: GenMessage<GetBlogPostResponse>;

/**
 * 取得部落格文章（包含 prompts）回應
 *
 * @generated from message blog_agent.v1.GetBlogPostWithPromptsResponse
 */
export declare type GetBlogPostWithPromptsResponse = Message<"blog_agent.v1.GetBlogPostWithPromptsResponse"> & {
  /**
   * @generated from field: blog_agent.v1.BlogPost blog_post = 1;
   */
  blogPost?: BlogPost;

  /**
   * 結構化的內容區塊
   *
   * @generated from field: repeated blog_agent.v1.ContentBlock content_blocks = 2;
   */
  contentBlocks: ContentBlock[];
};

/**
 * Describes the message blog_agent.v1.GetBlogPostWithPromptsResponse.
 * Use `create(GetBlogPostWithPromptsResponseSchema)` to create a new message.
 */
export declare const GetBlogPostWithPromptsResponseSchema: GenMessage<GetBlogPostWithPromptsResponse>;

/**
 * 列出部落格文章請求
 *
 * @generated from message blog_agent.v1.ListBlogPostsRequest
 */
export declare type ListBlogPostsRequest = Message<"blog_agent.v1.ListBlogPostsRequest"> & {
  /**
   * @generated from field: int32 page_size = 1;
   */
  pageSize: number;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken: string;

  /**
   * 狀態篩選（可選）
   *
   * @generated from field: blog_agent.v1.BlogPostStatus status_filter = 3;
   */
  statusFilter: BlogPostStatus;
};

/**
 * Describes the message blog_agent.v1.ListBlogPostsRequest.
 * Use `create(ListBlogPostsRequestSchema)` to create a new message.
 */
export declare const ListBlogPostsRequestSchema: GenMessage<ListBlogPostsRequest>;

/**
 * 列出部落格文章回應
 *
 * @generated from message blog_agent.v1.ListBlogPostsResponse
 */
export declare type ListBlogPostsResponse = Message<"blog_agent.v1.ListBlogPostsResponse"> & {
  /**
   * @generated from field: repeated blog_agent.v1.BlogPost blog_posts = 1;
   */
  blogPosts: BlogPost[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;

  /**
   * @generated from field: int32 total_count = 3;
   */
  totalCount: number;
};

/**
 * Describes the message blog_agent.v1.ListBlogPostsResponse.
 * Use `create(ListBlogPostsResponseSchema)` to create a new message.
 */
export declare const ListBlogPostsResponseSchema: GenMessage<ListBlogPostsResponse>;

/**
 * 取得處理歷史請求
 *
 * @generated from message blog_agent.v1.GetProcessingHistoryRequest
 */
export declare type GetProcessingHistoryRequest = Message<"blog_agent.v1.GetProcessingHistoryRequest"> & {
  /**
   * 處理 ID (UUID)
   *
   * @generated from field: string processing_id = 1;
   */
  processingId: string;
};

/**
 * Describes the message blog_agent.v1.GetProcessingHistoryRequest.
 * Use `create(GetProcessingHistoryRequestSchema)` to create a new message.
 */
export declare const GetProcessingHistoryRequestSchema: GenMessage<GetProcessingHistoryRequest>;

/**
 * 取得處理歷史回應
 *
 * @generated from message blog_agent.v1.GetProcessingHistoryResponse
 */
export declare type GetProcessingHistoryResponse = Message<"blog_agent.v1.GetProcessingHistoryResponse"> & {
  /**
   * @generated from field: blog_agent.v1.ProcessingHistory processing_history = 1;
   */
  processingHistory?: ProcessingHistory;
};

/**
 * Describes the message blog_agent.v1.GetProcessingHistoryResponse.
 * Use `create(GetProcessingHistoryResponseSchema)` to create a new message.
 */
export declare const GetProcessingHistoryResponseSchema: GenMessage<GetProcessingHistoryResponse>;

/**
 * 對話紀錄
 *
 * @generated from message blog_agent.v1.ConversationLog
 */
export declare type ConversationLog = Message<"blog_agent.v1.ConversationLog"> & {
  /**
   * UUID
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string file_path = 2;
   */
  filePath: string;

  /**
   * @generated from field: blog_agent.v1.FileFormat file_format = 3;
   */
  fileFormat: FileFormat;

  /**
   * 原始內容（文字）
   *
   * @generated from field: string raw_content = 4;
   */
  rawContent: string;

  /**
   * 解析後的 JSON 字串
   *
   * @generated from field: string parsed_content_json = 5;
   */
  parsedContentJson: string;

  /**
   * @generated from field: map<string, string> metadata = 6;
   */
  metadata: { [key: string]: string };

  /**
   * 偵測到的語言
   *
   * @generated from field: string language = 7;
   */
  language: string;

  /**
   * 訊息數量
   *
   * @generated from field: int32 message_count = 8;
   */
  messageCount: number;

  /**
   * ISO 8601 timestamp
   *
   * @generated from field: string created_at = 9;
   */
  createdAt: string;

  /**
   * @generated from field: string updated_at = 10;
   */
  updatedAt: string;
};

/**
 * Describes the message blog_agent.v1.ConversationLog.
 * Use `create(ConversationLogSchema)` to create a new message.
 */
export declare const ConversationLogSchema: GenMessage<ConversationLog>;

/**
 * 部落格文章
 *
 * @generated from message blog_agent.v1.BlogPost
 */
export declare type BlogPost = Message<"blog_agent.v1.BlogPost"> & {
  /**
   * UUID
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * 關聯的對話紀錄 ID
   *
   * @generated from field: string conversation_log_id = 2;
   */
  conversationLogId: string;

  /**
   * @generated from field: string title = 3;
   */
  title: string;

  /**
   * @generated from field: string summary = 4;
   */
  summary: string;

  /**
   * @generated from field: repeated string tags = 5;
   */
  tags: string[];

  /**
   * Markdown 格式（保留用於向後兼容）
   *
   * @generated from field: string content = 6;
   */
  content: string;

  /**
   * @generated from field: map<string, string> metadata = 7;
   */
  metadata: { [key: string]: string };

  /**
   * @generated from field: blog_agent.v1.BlogPostStatus status = 8;
   */
  status: BlogPostStatus;

  /**
   * ISO 8601 timestamp
   *
   * @generated from field: string created_at = 9;
   */
  createdAt: string;

  /**
   * @generated from field: string updated_at = 10;
   */
  updatedAt: string;
};

/**
 * Describes the message blog_agent.v1.BlogPost.
 * Use `create(BlogPostSchema)` to create a new message.
 */
export declare const BlogPostSchema: GenMessage<BlogPost>;

/**
 * 內容區塊（用於 UI/UX Side-by-Side 顯示）
 *
 * @generated from message blog_agent.v1.ContentBlock
 */
export declare type ContentBlock = Message<"blog_agent.v1.ContentBlock"> & {
  /**
   * UUID
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * 關聯的部落格文章 ID
   *
   * @generated from field: string blog_post_id = 2;
   */
  blogPostId: string;

  /**
   * 在文章中的順序（從 0 開始）
   *
   * @generated from field: int32 block_order = 3;
   */
  blockOrder: number;

  /**
   * 文章內容（Markdown 格式）
   *
   * @generated from field: string text = 4;
   */
  text: string;

  /**
   * 可選：對應的 Prompt 元資料（用於前端顯示）
   *
   * @generated from field: blog_agent.v1.PromptMeta prompt_meta = 5;
   */
  promptMeta?: PromptMeta;
};

/**
 * Describes the message blog_agent.v1.ContentBlock.
 * Use `create(ContentBlockSchema)` to create a new message.
 */
export declare const ContentBlockSchema: GenMessage<ContentBlock>;

/**
 * Prompt 元資料（用於前端 UI/UX 顯示）
 *
 * @generated from message blog_agent.v1.PromptMeta
 */
export declare type PromptMeta = Message<"blog_agent.v1.PromptMeta"> & {
  /**
   * 原始提問
   *
   * @generated from field: string original_prompt = 1;
   */
  originalPrompt: string;

  /**
   * AI 診斷
   *
   * @generated from field: string analysis = 2;
   */
  analysis: string;

  /**
   * 優化建議候選
   *
   * @generated from field: repeated blog_agent.v1.PromptCandidate better_candidates = 3;
   */
  betterCandidates: PromptCandidate[];

  /**
   * 預期效果說明
   *
   * @generated from field: string expected_effect = 4;
   */
  expectedEffect: string;
};

/**
 * Describes the message blog_agent.v1.PromptMeta.
 * Use `create(PromptMetaSchema)` to create a new message.
 */
export declare const PromptMetaSchema: GenMessage<PromptMeta>;

/**
 * Prompt 候選（結構化）
 *
 * @generated from message blog_agent.v1.PromptCandidate
 */
export declare type PromptCandidate = Message<"blog_agent.v1.PromptCandidate"> & {
  /**
   * 'structured' | 'role-play' | 'chain-of-thought'
   *
   * @generated from field: string type = 1;
   */
  type: string;

  /**
   * 優化後的 Prompt
   *
   * @generated from field: string prompt = 2;
   */
  prompt: string;

  /**
   * 為什麼這個版本更好
   *
   * @generated from field: string reasoning = 3;
   */
  reasoning: string;
};

/**
 * Describes the message blog_agent.v1.PromptCandidate.
 * Use `create(PromptCandidateSchema)` to create a new message.
 */
export declare const PromptCandidateSchema: GenMessage<PromptCandidate>;

/**
 * 處理歷史
 *
 * @generated from message blog_agent.v1.ProcessingHistory
 */
export declare type ProcessingHistory = Message<"blog_agent.v1.ProcessingHistory"> & {
  /**
   * UUID
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string conversation_log_id = 2;
   */
  conversationLogId: string;

  /**
   * 可選，如果處理成功
   *
   * @generated from field: string blog_post_id = 3;
   */
  blogPostId: string;

  /**
   * @generated from field: blog_agent.v1.ProcessingStatus status = 4;
   */
  status: ProcessingStatus;

  /**
   * 如果失敗，錯誤訊息
   *
   * @generated from field: string error_message = 5;
   */
  errorMessage: string;

  /**
   * 各步驟的 JSON 字串
   *
   * @generated from field: string processing_steps_json = 6;
   */
  processingStepsJson: string;

  /**
   * ISO 8601 timestamp
   *
   * @generated from field: string started_at = 7;
   */
  startedAt: string;

  /**
   * ISO 8601 timestamp（可選）
   *
   * @generated from field: string completed_at = 8;
   */
  completedAt: string;

  /**
   * @generated from field: string created_at = 9;
   */
  createdAt: string;
};

/**
 * Describes the message blog_agent.v1.ProcessingHistory.
 * Use `create(ProcessingHistorySchema)` to create a new message.
 */
export declare const ProcessingHistorySchema: GenMessage<ProcessingHistory>;

/**
 * 檔案格式
 *
 * @generated from enum blog_agent.v1.FileFormat
 */
export enum FileFormat {
  /**
   * @generated from enum value: FILE_FORMAT_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: FILE_FORMAT_MARKDOWN = 1;
   */
  MARKDOWN = 1,

  /**
   * @generated from enum value: FILE_FORMAT_JSON = 2;
   */
  JSON = 2,

  /**
   * @generated from enum value: FILE_FORMAT_CSV = 3;
   */
  CSV = 3,

  /**
   * @generated from enum value: FILE_FORMAT_TEXT = 4;
   */
  TEXT = 4,
}

/**
 * Describes the enum blog_agent.v1.FileFormat.
 */
export declare const FileFormatSchema: GenEnum<FileFormat>;

/**
 * 處理狀態
 *
 * @generated from enum blog_agent.v1.ProcessingStatus
 */
export enum ProcessingStatus {
  /**
   * @generated from enum value: PROCESSING_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: PROCESSING_STATUS_PENDING = 1;
   */
  PENDING = 1,

  /**
   * @generated from enum value: PROCESSING_STATUS_PROCESSING = 2;
   */
  PROCESSING = 2,

  /**
   * @generated from enum value: PROCESSING_STATUS_COMPLETED = 3;
   */
  COMPLETED = 3,

  /**
   * @generated from enum value: PROCESSING_STATUS_FAILED = 4;
   */
  FAILED = 4,
}

/**
 * Describes the enum blog_agent.v1.ProcessingStatus.
 */
export declare const ProcessingStatusSchema: GenEnum<ProcessingStatus>;

/**
 * 部落格文章狀態
 *
 * @generated from enum blog_agent.v1.BlogPostStatus
 */
export enum BlogPostStatus {
  /**
   * @generated from enum value: BLOG_POST_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: BLOG_POST_STATUS_DRAFT = 1;
   */
  DRAFT = 1,

  /**
   * @generated from enum value: BLOG_POST_STATUS_PUBLISHED = 2;
   */
  PUBLISHED = 2,

  /**
   * @generated from enum value: BLOG_POST_STATUS_ARCHIVED = 3;
   */
  ARCHIVED = 3,
}

/**
 * Describes the enum blog_agent.v1.BlogPostStatus.
 */
export declare const BlogPostStatusSchema: GenEnum<BlogPostStatus>;

/**
 * Blog Agent Service - 處理對話紀錄轉換為部落格文章
 *
 * @generated from service blog_agent.v1.BlogAgentService
 */
export declare const BlogAgentService: GenService<{
  /**
   * 處理對話紀錄並生成部落格文章
   *
   * @generated from rpc blog_agent.v1.BlogAgentService.ProcessConversation
   */
  processConversation: {
    methodKind: "unary";
    input: typeof ProcessConversationRequestSchema;
    output: typeof ProcessConversationResponseSchema;
  },
  /**
   * 列出所有已處理的對話紀錄
   *
   * @generated from rpc blog_agent.v1.BlogAgentService.ListConversationLogs
   */
  listConversationLogs: {
    methodKind: "unary";
    input: typeof ListConversationLogsRequestSchema;
    output: typeof ListConversationLogsResponseSchema;
  },
  /**
   * 取得特定的對話紀錄
   *
   * @generated from rpc blog_agent.v1.BlogAgentService.GetConversationLog
   */
  getConversationLog: {
    methodKind: "unary";
    input: typeof GetConversationLogRequestSchema;
    output: typeof GetConversationLogResponseSchema;
  },
  /**
   * 取得生成的部落格文章
   *
   * @generated from rpc blog_agent.v1.BlogAgentService.GetBlogPost
   */
  getBlogPost: {
    methodKind: "unary";
    input: typeof GetBlogPostRequestSchema;
    output: typeof GetBlogPostResponseSchema;
  },
  /**
   * 取得部落格文章（包含結構化的 content blocks 和 prompt meta，用於 UI/UX）
   *
   * @generated from rpc blog_agent.v1.BlogAgentService.GetBlogPostWithPrompts
   */
  getBlogPostWithPrompts: {
    methodKind: "unary";
    input: typeof GetBlogPostRequestSchema;
    output: typeof GetBlogPostWithPromptsResponseSchema;
  },
  /**
   * 列出所有部落格文章
   *
   * @generated from rpc blog_agent.v1.BlogAgentService.ListBlogPosts
   */
  listBlogPosts: {
    methodKind: "unary";
    input: typeof ListBlogPostsRequestSchema;
    output: typeof ListBlogPostsResponseSchema;
  },
  /**
   * 取得處理歷史
   *
   * @generated from rpc blog_agent.v1.BlogAgentService.GetProcessingHistory
   */
  getProcessingHistory: {
    methodKind: "unary";
    input: typeof GetProcessingHistoryRequestSchema;
    output: typeof GetProcessingHistoryResponseSchema;
  },
}>;

