// @generated by protoc-gen-connect-es v0.13.0
// @generated from file blog_agent.proto (package blog_agent.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetBlogPostRequest, GetBlogPostResponse, GetBlogPostWithPromptsResponse, GetConversationLogRequest, GetConversationLogResponse, GetProcessingHistoryRequest, GetProcessingHistoryResponse, ListBlogPostsRequest, ListBlogPostsResponse, ListConversationLogsRequest, ListConversationLogsResponse, ProcessConversationRequest, ProcessConversationResponse } from "./blog_agent_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Blog Agent Service - 處理對話紀錄轉換為部落格文章
 *
 * @generated from service blog_agent.v1.BlogAgentService
 */
export const BlogAgentService = {
  typeName: "blog_agent.v1.BlogAgentService",
  methods: {
    /**
     * 處理對話紀錄並生成部落格文章
     *
     * @generated from rpc blog_agent.v1.BlogAgentService.ProcessConversation
     */
    processConversation: {
      name: "ProcessConversation",
      I: ProcessConversationRequest,
      O: ProcessConversationResponse,
      kind: MethodKind.Unary,
    },
    /**
     * 列出所有已處理的對話紀錄
     *
     * @generated from rpc blog_agent.v1.BlogAgentService.ListConversationLogs
     */
    listConversationLogs: {
      name: "ListConversationLogs",
      I: ListConversationLogsRequest,
      O: ListConversationLogsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * 取得特定的對話紀錄
     *
     * @generated from rpc blog_agent.v1.BlogAgentService.GetConversationLog
     */
    getConversationLog: {
      name: "GetConversationLog",
      I: GetConversationLogRequest,
      O: GetConversationLogResponse,
      kind: MethodKind.Unary,
    },
    /**
     * 取得生成的部落格文章
     *
     * @generated from rpc blog_agent.v1.BlogAgentService.GetBlogPost
     */
    getBlogPost: {
      name: "GetBlogPost",
      I: GetBlogPostRequest,
      O: GetBlogPostResponse,
      kind: MethodKind.Unary,
    },
    /**
     * 取得部落格文章（包含結構化的 content blocks 和 prompt meta，用於 UI/UX）
     *
     * @generated from rpc blog_agent.v1.BlogAgentService.GetBlogPostWithPrompts
     */
    getBlogPostWithPrompts: {
      name: "GetBlogPostWithPrompts",
      I: GetBlogPostRequest,
      O: GetBlogPostWithPromptsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * 列出所有部落格文章
     *
     * @generated from rpc blog_agent.v1.BlogAgentService.ListBlogPosts
     */
    listBlogPosts: {
      name: "ListBlogPosts",
      I: ListBlogPostsRequest,
      O: ListBlogPostsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * 取得處理歷史
     *
     * @generated from rpc blog_agent.v1.BlogAgentService.GetProcessingHistory
     */
    getProcessingHistory: {
      name: "GetProcessingHistory",
      I: GetProcessingHistoryRequest,
      O: GetProcessingHistoryResponse,
      kind: MethodKind.Unary,
    },
  }
};

