# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: blog_agent.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import blog_agent_pb2 as blog__agent__pb2


class BlogAgentService(Protocol):
    async def process_conversation(self, request: blog__agent__pb2.ProcessConversationRequest, ctx: RequestContext) -> blog__agent__pb2.ProcessConversationResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_conversation_logs(self, request: blog__agent__pb2.ListConversationLogsRequest, ctx: RequestContext) -> blog__agent__pb2.ListConversationLogsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_conversation_log(self, request: blog__agent__pb2.GetConversationLogRequest, ctx: RequestContext) -> blog__agent__pb2.GetConversationLogResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_blog_post(self, request: blog__agent__pb2.GetBlogPostRequest, ctx: RequestContext) -> blog__agent__pb2.GetBlogPostResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_blog_post_with_prompts(self, request: blog__agent__pb2.GetBlogPostRequest, ctx: RequestContext) -> blog__agent__pb2.GetBlogPostWithPromptsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_blog_posts(self, request: blog__agent__pb2.ListBlogPostsRequest, ctx: RequestContext) -> blog__agent__pb2.ListBlogPostsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_processing_history(self, request: blog__agent__pb2.GetProcessingHistoryRequest, ctx: RequestContext) -> blog__agent__pb2.GetProcessingHistoryResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def extract_conversation_facts(self, request: blog__agent__pb2.ExtractConversationFactsRequest, ctx: RequestContext) -> blog__agent__pb2.ExtractConversationFactsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class BlogAgentServiceASGIApplication(ConnectASGIApplication[BlogAgentService]):
    def __init__(self, service: BlogAgentService | AsyncGenerator[BlogAgentService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/blog_agent.v1.BlogAgentService/ProcessConversation": Endpoint.unary(
                    method=MethodInfo(
                        name="ProcessConversation",
                        service_name="blog_agent.v1.BlogAgentService",
                        input=blog__agent__pb2.ProcessConversationRequest,
                        output=blog__agent__pb2.ProcessConversationResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.process_conversation,
                ),
                "/blog_agent.v1.BlogAgentService/ListConversationLogs": Endpoint.unary(
                    method=MethodInfo(
                        name="ListConversationLogs",
                        service_name="blog_agent.v1.BlogAgentService",
                        input=blog__agent__pb2.ListConversationLogsRequest,
                        output=blog__agent__pb2.ListConversationLogsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_conversation_logs,
                ),
                "/blog_agent.v1.BlogAgentService/GetConversationLog": Endpoint.unary(
                    method=MethodInfo(
                        name="GetConversationLog",
                        service_name="blog_agent.v1.BlogAgentService",
                        input=blog__agent__pb2.GetConversationLogRequest,
                        output=blog__agent__pb2.GetConversationLogResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_conversation_log,
                ),
                "/blog_agent.v1.BlogAgentService/GetBlogPost": Endpoint.unary(
                    method=MethodInfo(
                        name="GetBlogPost",
                        service_name="blog_agent.v1.BlogAgentService",
                        input=blog__agent__pb2.GetBlogPostRequest,
                        output=blog__agent__pb2.GetBlogPostResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_blog_post,
                ),
                "/blog_agent.v1.BlogAgentService/GetBlogPostWithPrompts": Endpoint.unary(
                    method=MethodInfo(
                        name="GetBlogPostWithPrompts",
                        service_name="blog_agent.v1.BlogAgentService",
                        input=blog__agent__pb2.GetBlogPostRequest,
                        output=blog__agent__pb2.GetBlogPostWithPromptsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_blog_post_with_prompts,
                ),
                "/blog_agent.v1.BlogAgentService/ListBlogPosts": Endpoint.unary(
                    method=MethodInfo(
                        name="ListBlogPosts",
                        service_name="blog_agent.v1.BlogAgentService",
                        input=blog__agent__pb2.ListBlogPostsRequest,
                        output=blog__agent__pb2.ListBlogPostsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_blog_posts,
                ),
                "/blog_agent.v1.BlogAgentService/GetProcessingHistory": Endpoint.unary(
                    method=MethodInfo(
                        name="GetProcessingHistory",
                        service_name="blog_agent.v1.BlogAgentService",
                        input=blog__agent__pb2.GetProcessingHistoryRequest,
                        output=blog__agent__pb2.GetProcessingHistoryResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_processing_history,
                ),
                "/blog_agent.v1.BlogAgentService/ExtractConversationFacts": Endpoint.unary(
                    method=MethodInfo(
                        name="ExtractConversationFacts",
                        service_name="blog_agent.v1.BlogAgentService",
                        input=blog__agent__pb2.ExtractConversationFactsRequest,
                        output=blog__agent__pb2.ExtractConversationFactsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.extract_conversation_facts,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/blog_agent.v1.BlogAgentService"


class BlogAgentServiceClient(ConnectClient):
    async def process_conversation(
        self,
        request: blog__agent__pb2.ProcessConversationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> blog__agent__pb2.ProcessConversationResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ProcessConversation",
                service_name="blog_agent.v1.BlogAgentService",
                input=blog__agent__pb2.ProcessConversationRequest,
                output=blog__agent__pb2.ProcessConversationResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_conversation_logs(
        self,
        request: blog__agent__pb2.ListConversationLogsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> blog__agent__pb2.ListConversationLogsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListConversationLogs",
                service_name="blog_agent.v1.BlogAgentService",
                input=blog__agent__pb2.ListConversationLogsRequest,
                output=blog__agent__pb2.ListConversationLogsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_conversation_log(
        self,
        request: blog__agent__pb2.GetConversationLogRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> blog__agent__pb2.GetConversationLogResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetConversationLog",
                service_name="blog_agent.v1.BlogAgentService",
                input=blog__agent__pb2.GetConversationLogRequest,
                output=blog__agent__pb2.GetConversationLogResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_blog_post(
        self,
        request: blog__agent__pb2.GetBlogPostRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> blog__agent__pb2.GetBlogPostResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetBlogPost",
                service_name="blog_agent.v1.BlogAgentService",
                input=blog__agent__pb2.GetBlogPostRequest,
                output=blog__agent__pb2.GetBlogPostResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_blog_post_with_prompts(
        self,
        request: blog__agent__pb2.GetBlogPostRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> blog__agent__pb2.GetBlogPostWithPromptsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetBlogPostWithPrompts",
                service_name="blog_agent.v1.BlogAgentService",
                input=blog__agent__pb2.GetBlogPostRequest,
                output=blog__agent__pb2.GetBlogPostWithPromptsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_blog_posts(
        self,
        request: blog__agent__pb2.ListBlogPostsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> blog__agent__pb2.ListBlogPostsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListBlogPosts",
                service_name="blog_agent.v1.BlogAgentService",
                input=blog__agent__pb2.ListBlogPostsRequest,
                output=blog__agent__pb2.ListBlogPostsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_processing_history(
        self,
        request: blog__agent__pb2.GetProcessingHistoryRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> blog__agent__pb2.GetProcessingHistoryResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetProcessingHistory",
                service_name="blog_agent.v1.BlogAgentService",
                input=blog__agent__pb2.GetProcessingHistoryRequest,
                output=blog__agent__pb2.GetProcessingHistoryResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def extract_conversation_facts(
        self,
        request: blog__agent__pb2.ExtractConversationFactsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> blog__agent__pb2.ExtractConversationFactsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ExtractConversationFacts",
                service_name="blog_agent.v1.BlogAgentService",
                input=blog__agent__pb2.ExtractConversationFactsRequest,
                output=blog__agent__pb2.ExtractConversationFactsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class BlogAgentServiceSync(Protocol):
    def process_conversation(self, request: blog__agent__pb2.ProcessConversationRequest, ctx: RequestContext) -> blog__agent__pb2.ProcessConversationResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_conversation_logs(self, request: blog__agent__pb2.ListConversationLogsRequest, ctx: RequestContext) -> blog__agent__pb2.ListConversationLogsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_conversation_log(self, request: blog__agent__pb2.GetConversationLogRequest, ctx: RequestContext) -> blog__agent__pb2.GetConversationLogResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_blog_post(self, request: blog__agent__pb2.GetBlogPostRequest, ctx: RequestContext) -> blog__agent__pb2.GetBlogPostResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_blog_post_with_prompts(self, request: blog__agent__pb2.GetBlogPostRequest, ctx: RequestContext) -> blog__agent__pb2.GetBlogPostWithPromptsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_blog_posts(self, request: blog__agent__pb2.ListBlogPostsRequest, ctx: RequestContext) -> blog__agent__pb2.ListBlogPostsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_processing_history(self, request: blog__agent__pb2.GetProcessingHistoryRequest, ctx: RequestContext) -> blog__agent__pb2.GetProcessingHistoryResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def extract_conversation_facts(self, request: blog__agent__pb2.ExtractConversationFactsRequest, ctx: RequestContext) -> blog__agent__pb2.ExtractConversationFactsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class BlogAgentServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: BlogAgentServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/blog_agent.v1.BlogAgentService/ProcessConversation": EndpointSync.unary(
                    method=MethodInfo(
                        name="ProcessConversation",
                        service_name="blog_agent.v1.BlogAgentService",
                        input=blog__agent__pb2.ProcessConversationRequest,
                        output=blog__agent__pb2.ProcessConversationResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.process_conversation,
                ),
                "/blog_agent.v1.BlogAgentService/ListConversationLogs": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListConversationLogs",
                        service_name="blog_agent.v1.BlogAgentService",
                        input=blog__agent__pb2.ListConversationLogsRequest,
                        output=blog__agent__pb2.ListConversationLogsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_conversation_logs,
                ),
                "/blog_agent.v1.BlogAgentService/GetConversationLog": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetConversationLog",
                        service_name="blog_agent.v1.BlogAgentService",
                        input=blog__agent__pb2.GetConversationLogRequest,
                        output=blog__agent__pb2.GetConversationLogResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_conversation_log,
                ),
                "/blog_agent.v1.BlogAgentService/GetBlogPost": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetBlogPost",
                        service_name="blog_agent.v1.BlogAgentService",
                        input=blog__agent__pb2.GetBlogPostRequest,
                        output=blog__agent__pb2.GetBlogPostResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_blog_post,
                ),
                "/blog_agent.v1.BlogAgentService/GetBlogPostWithPrompts": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetBlogPostWithPrompts",
                        service_name="blog_agent.v1.BlogAgentService",
                        input=blog__agent__pb2.GetBlogPostRequest,
                        output=blog__agent__pb2.GetBlogPostWithPromptsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_blog_post_with_prompts,
                ),
                "/blog_agent.v1.BlogAgentService/ListBlogPosts": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListBlogPosts",
                        service_name="blog_agent.v1.BlogAgentService",
                        input=blog__agent__pb2.ListBlogPostsRequest,
                        output=blog__agent__pb2.ListBlogPostsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_blog_posts,
                ),
                "/blog_agent.v1.BlogAgentService/GetProcessingHistory": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetProcessingHistory",
                        service_name="blog_agent.v1.BlogAgentService",
                        input=blog__agent__pb2.GetProcessingHistoryRequest,
                        output=blog__agent__pb2.GetProcessingHistoryResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_processing_history,
                ),
                "/blog_agent.v1.BlogAgentService/ExtractConversationFacts": EndpointSync.unary(
                    method=MethodInfo(
                        name="ExtractConversationFacts",
                        service_name="blog_agent.v1.BlogAgentService",
                        input=blog__agent__pb2.ExtractConversationFactsRequest,
                        output=blog__agent__pb2.ExtractConversationFactsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.extract_conversation_facts,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/blog_agent.v1.BlogAgentService"


class BlogAgentServiceClientSync(ConnectClientSync):
    def process_conversation(
        self,
        request: blog__agent__pb2.ProcessConversationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> blog__agent__pb2.ProcessConversationResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ProcessConversation",
                service_name="blog_agent.v1.BlogAgentService",
                input=blog__agent__pb2.ProcessConversationRequest,
                output=blog__agent__pb2.ProcessConversationResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_conversation_logs(
        self,
        request: blog__agent__pb2.ListConversationLogsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> blog__agent__pb2.ListConversationLogsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListConversationLogs",
                service_name="blog_agent.v1.BlogAgentService",
                input=blog__agent__pb2.ListConversationLogsRequest,
                output=blog__agent__pb2.ListConversationLogsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_conversation_log(
        self,
        request: blog__agent__pb2.GetConversationLogRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> blog__agent__pb2.GetConversationLogResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetConversationLog",
                service_name="blog_agent.v1.BlogAgentService",
                input=blog__agent__pb2.GetConversationLogRequest,
                output=blog__agent__pb2.GetConversationLogResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_blog_post(
        self,
        request: blog__agent__pb2.GetBlogPostRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> blog__agent__pb2.GetBlogPostResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetBlogPost",
                service_name="blog_agent.v1.BlogAgentService",
                input=blog__agent__pb2.GetBlogPostRequest,
                output=blog__agent__pb2.GetBlogPostResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_blog_post_with_prompts(
        self,
        request: blog__agent__pb2.GetBlogPostRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> blog__agent__pb2.GetBlogPostWithPromptsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetBlogPostWithPrompts",
                service_name="blog_agent.v1.BlogAgentService",
                input=blog__agent__pb2.GetBlogPostRequest,
                output=blog__agent__pb2.GetBlogPostWithPromptsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_blog_posts(
        self,
        request: blog__agent__pb2.ListBlogPostsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> blog__agent__pb2.ListBlogPostsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListBlogPosts",
                service_name="blog_agent.v1.BlogAgentService",
                input=blog__agent__pb2.ListBlogPostsRequest,
                output=blog__agent__pb2.ListBlogPostsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_processing_history(
        self,
        request: blog__agent__pb2.GetProcessingHistoryRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> blog__agent__pb2.GetProcessingHistoryResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetProcessingHistory",
                service_name="blog_agent.v1.BlogAgentService",
                input=blog__agent__pb2.GetProcessingHistoryRequest,
                output=blog__agent__pb2.GetProcessingHistoryResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def extract_conversation_facts(
        self,
        request: blog__agent__pb2.ExtractConversationFactsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> blog__agent__pb2.ExtractConversationFactsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ExtractConversationFacts",
                service_name="blog_agent.v1.BlogAgentService",
                input=blog__agent__pb2.ExtractConversationFactsRequest,
                output=blog__agent__pb2.ExtractConversationFactsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
